### ISSUE TITLE
Crashes when shown

### ISSUE THREAD

**Issue by AVESUM** [gruppe-adler/grad-passport#3]
I tried grad_passport but it keeps crashing the game. 
Works to look at my own, and look at AIs. But instantly crashes when I show my ID to AI or player. 

Only running CBA_A3 and ace. Latest Steam workshop releases.

**Comment by McDiod** [comment]
I'm unable to reproduce this. Can you post the mission that you are testing this with?

**Comment by AVESUM** [comment]
Absolutely! I started big but slimmed it down to this: 
https://drive.google.com/file/d/1LHpGn8Li3nmVlvVlSz-YdIc6KE2XA77C/view?usp=sharing

This version is only tested on local multiplayer, but another version on dedicated.

**Comment by McDiod** [comment]
I'm still unable to reproduce this, be it SP, local MP or dedicated.

See if this version works for you:
[_temp_ID.Malden.zip](https://github.com/gruppe-adler/grad-passport/files/4176736/_temp_ID.Malden.zip)

If it does then release [0.0.4](https://github.com/gruppe-adler/grad-passport/releases/tag/0.0.4) fixed it. If it doesn't please post your .rpt, which you can find in `C:\Users\Username\AppData\Local\Arma 3`.

**Comment by AVESUM** [comment]
Works perfectly and as intended!
